version: '3.3'
services:
  postgres:
    image: 'postgres:13.2'
    ports:
      - "5432:5432"
    networks:
      - app_net
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: uber
    volumes:
      - ./docker-postgresql-data-for-dev:/var/lib/postgresql/data

networks:
  app_net:
    driver: bridge
